---
version: '3'
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    environment:
      - PUID=${BRUFLIX_ID}
      - PGID=${BRUFLIX_ID}
      - TZ=${TZ}
      - VERSION=docker
    volumes:
      - ${APP_DIR}/plex:/config
      - ${MEDIA_DIR}/tv:/tv
      - ${MEDIA_DIR}/movies:/movies
      - ${MEDIA_DIR}/dvr:/dvr
    network_mode: host
    restart: unless-stopped

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${BRUFLIX_ID}
      - PGID=${BRUFLIX_ID}
      - TZ=America/Denver
    volumes:
      - ${APP_DIR}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped